language: csharp

environment:
  solutionFile: server.sln

notifications:
  slack: skinsroulette:FngoFqVgw37UgZ2MowuUcl20
  
install:
  - sudo apt-get install nunit-console
  - nuget restore %solutionFile%
  
script:
  - xbuild .server/server.sln